TITLE = "Anzahl der schriftlichen Klausuren in der Prüfungsanforderung"

CONTENT = ( " Aus eigener Erfahrung sind die starken Fokussierung auf schriftliche Klausuren als Hauptleistungsnachweis ein großes Problem. "
            " Im echten Berufsleben geht es selten darum, unter Zeitdruck in 1–3 Stunden isoliertes Wissen abzurufen. "
            " Stattdessen zählen  Teamarbeit, Präsentationen, Projektmanagement und die Fähigkeit, kontinuierlich Lösungen zu erarbeiten."
            " Doch im Studium wird oft fast die gesamte Note von einer einzigen Klausur abhängig gemacht,"
            " was weder die tatsächlichen Kompetenzen noch die Arbeitsrealität widerspiegelt.\n\n"
            " Besonders frustrierend finde ich, dass viele Studierende, mich eingeschlossen, stundenlang für eine Prüfung lernen, "
            " die am Ende nur einen künstlichen Ausschnitt des Gelernten abfragt."
            " Gleichzeitig werden praktische Fähigkeiten, wie das Arbeiten im Team oder das Präsentieren von Ergebnissen, oft nur am Rande bewertet "
            " obwohl genau diese Skills im Berufsalltag meiner Meinung nach entscheidend sind."
            " Ich habe selbst erlebt, wie Kommilitone, die in Klausuren glänzten, in Gruppenprojekten "
            " oder bei mündlichen Präsentationen Schwierigkeiten hatten und umgekehrt.\n\n "
            " Meiner Meinung nach sollte das Bewertungssystem diverser gestaltet werden."
            " Schriftliche Prüfungen müssen nicht komplett abgeschafft werden, aber sie sollten nur einen Teil der Note ausmachen."
            " Stattdessen könnten Gruppenarbeiten, Projektberichte, Vorträge oder kontinuierliche Leistungsnachweise stärker gewichtet werden."
            " Das würde meienr Meinung nach nicht nur die Realitätsnähe erhöhen, sondern auch verschiedene Stärken der Studierenden besser abbilden. "
            " Zudem würde es den Lernprozess entzerren, da nicht alles auf eine einzige Prüfung hinausläuft.\n\n "
            " ### Autor: Florian Luzemann\n ")