# Created by Milan Littfin on 18.01.2026

TITLE = "Reine Frontalvorlesungen sind nicht modern"

CONTENT = ("Meiner Meinung nach sind reine Frontalvorlesungen, wie sie an der Technischen Hochschule teilweise noch "
           "durchgeführt werden, nicht mehr zeitgemäß. Sie sollten durch modernere Lehrverfahren ergänzt oder "
           "abgelöst werden.\n"
           "Ein konkretes Beispiel war das Fach EBR: Die Vorlesung wurde sehr eintönig gestaltet, was es schwer "
           "machte, sich über den gesamten Zeitraum zu konzentrieren. Da die Inhalte der Vorlesung fast identisch "
           "mit den bereitgestellten Folien waren, bot der Besuch der Veranstaltung kaum einen Mehrwert gegenüber "
           "dem Selbststudium. Grundsätzlich sollte es nicht effizienter sein, die Folien alleine zu lesen, als an "
           "der eigentlichen Vorlesung teilzunehmen. In meinem Fall führte dies dazu, dass ich die Vorlesung nach "
           "dem dritten Termin nicht mehr besucht habe, da der Lerneffekt vor Ort zu gering war.\n\n"
           "Glücklicherweise gibt es moderne Methoden der Wissensvermittlung, die das Engagement und die Motivation "
           "der Studierenden deutlich erhöhen könnten. Zum Beispiel Praxisbezug: Der Fokus sollte von der reinen "
           "Theorie stärker ins Praktische gerückt werden, um das Interesse am Gelernten zu wecken. Zentral ist "
           "auch, dass die Professoren ihre Lehrveranstaltungen so gestalten, dass die Studierenden neugierig auf "
           "mehr des Gelehrten werden.\n"
           "Eine andere Alternative zur reinen Frontalvorlesung, Peer-Instruction: Hierbei stellt der Dozent nach "
           "einem Themenblock Verständnisfragen, die jeder Studierende zunächst selbst beantwortet. Bei vielen "
           "falschen Antworten diskutieren die Studierenden kurz mit ihren Sitznachbarn. Da Studierende oft eine‚ "
           "ähnliche Sprache‘ sprechen, können sie sich komplexe Sachverhalte untereinander oft verständlicher "
           "erklären.\n"
           "Ein weiterer Vorschlag, Gamification: Elemente aus Spielen wie Punkte und Quests werden in die Lehre "
           "integriert. Als Beispiel können Programmier-Challenges aufgegeben werden, bei welchen sich die Studierenden "
           "untereinander messen damit sie sich intensiver mit den Aufgaben auseinandersetzen und so eine höhere "
           "Lernbereitschaft und Engagement an den Tag legen.\n"
           "Als anderen Vorschlag um reine Frontalvorlesungen zu ersetzen, seminaristischer Unterricht: "
           "Der Dozent hält Kurzvorträge und die Studierenden finden sich dazu entweder in Diskussionsrunden "
           "ein oder erhalten Einzel- beziehungsweise Partneraufgaben.\n"
           "Der letzte Vorschlag, Micro-Learning durch Lernvideos: Anstelle von langen Präsenzvorlesungen "
           "könnten kleine, vorbereitete Videos zu spezifischen Themenblöcken angeboten werden. Dies hilft dabei, "
           "die Aufmerksamkeitsspanne nicht zu überfordern, und ermöglichst es den Studierenden, Inhalte im eigenen "
           "Tempo zu erarbeiten und schwierige Stellen bei Bedarf mehrmals anzusehen. Ähnlich hat es zum Beispiel das "
           "Fach Paradigmen der Programmierung gemacht. So konnten die Studierenden sich die Informationen im eigenen "
           "Tempo aneignen und sie konnten gut vorbereitet zu den Übungen gehen um unklarheiten aus den "
           "Lernvideos mit dem Dozenten zu besprechen.\n\n"
           "Ziel der Lehrveranstaltungen sollte es sein, diese so zu gestalten, dass Studierende neugierig auf die "
           "Inhalte werden und die Präsenzzeit an der Uni beziehungsweise in den Vorlesungssälen als Gewinnbringend "
           "für ihren Lernerfolg sehen.\n\n"
           "### Autor: Milan Littfin\n")