TITLE="Abgaben nicht zu spät anfangen"
CONTENT=("Während meiner Zeit an der Uni hatte ich ständig mit einer Flut an Abgaben für die verschiedensten Module zu kämpfen.\n"
             " Mein größtes Problem dabei war, dass ich vieles bis zum allerletzten Drücker aufgeschoben habe,\n"
             " was natürlich regelmäßig für extremen Stress gesorgt hat. Ein perfektes Beispiel dafür war das Modul „Software-Technik 2“.\n"
             " Dort hatten wir alle zwei Wochen eine Abgabe, wobei jeder Schritt direkt auf dem vorherigen aufgebaut hat:\n"
             " In der ersten Woche mussten wir das Programm grundlegend aufsetzen,\n"
             " in der zweiten wurde es mit SpringBoot und UUIDs umgeschrieben,\n"
             " danach folgte eine Phase, um den Code sauberer zu strukturieren, u\n"
             "nd am Ende sollte das Ganze mit Hilfe von HTTP und DTOs vollendet werden.\n"
             "Obwohl für jeden dieser Meilensteine gute zwei Wochen Zeit angesetzt waren,\n"
             " war mein Standardgedanke immer: „Ach, das bisschen Arbeit erledige ich locker am Wochenende davor.\n"
             "Das hat sich oft als Trugschluss herausgestellt, da man den Aufwand völlig unterschätzt,\n"
             " wenn man noch so viel vor sich hat.\n"
             " In den meisten Fällen bin ich damit gerade noch so durchgekommen,\n"
             " doch beim letzten Meilenstein ist mir das Ganze dann um die Ohren geflogen.\n"
             " Durch einen sehr dummen Fehler funktionierte plötzlich das gesamte Programm nicht mehr.\n"
             " Da ich keinen Zeitpuffer mehr hatte, konnte ich das Problem nicht rechtzeitig lösen,\n"
             " was letztendlich dazu führte, dass ich das Praktikum nicht bestanden habe. \n"
             "###Autor: Daniel Hans Gabor")