# Created by Timon Kirch on 17.01.2026

"""
Auswertungen aus der Umfrage von
"Evaluation des Studiengangs Informatik (B.A.) - Studentische Perspektiven für die Reakkreditierung an der TH-Köln"
"""

TITEL = "Auswertung - Wie würdest du die Angebote in den jeweiligen Themenbereichen anhand der Menge bewerten?"

CONTENT = ("### Auswertung des Diagramms: Wie würdest du die Angebote in den jeweiligen "
           "Themenbereichen anhand der Menge bewerten? \n\n"
           "In unserer Umfrage wurde den Studenten die Frage gestellt, inwieweit sie mit der Menge an Angeboten in "
           "bestimmten Themenbereichen zufrieden sind. Die Themenbereiche waren ‚Hardware‘, ‚KI‘, ‚IT-Sicherheit‘, "
           "‚IT-Management‘, ‚Frontend-Entwicklung‘ und ‚Backend-Entwicklung‘. Sie konnten für die Bewertung der "
           "Themen zwischen den Optionen ‚Sehr Wenig‘, ‚Wenig‘, ‚Genau richtig‘, ‚Viel‘ und ‚Sehr Viel‘ wählen."
           "Im Themenfeld ‚Hardware‘ reichen die Antworten von ‚Wenig‘ bis ‚Viel‘, wobei fünf Siebtel der Antworten "
           "für die Option ‚Wenig‘ abgegeben wurden. Daher lässt sich annehmen, dass ein Großteil der Befragten sich "
           "ein größeres Angebot zum Thema ‚Hardware‘ wünschen würden. \n\n"
           "Im Themenfeld ‚KI‘ wurden die Antworten auch alle zwischen ‚Wenig‘ und ‚Viel‘ angegeben. Jedoch hat hier "
           "nur ein Siebtel der Befragten angegeben, dass das Angebot ‚Wenig‘ sei. Vier Siebtel der Befragten gaben "
           "an, dass die Menge an Angeboten zu ‚KI‘ ‚Genau richtig‘ sei und zwei Siebtel der Befragten gaben an, "
           "dass es viele Angebote zum Thema KI gäbe. Die Ergebnisse führen mich zu der Annahme, dass die Befragten "
           "das Angebot für sehr umfangreich halten, aber es Ihnen noch nicht zu viel wird, mehr Angebote aber auch "
           "nicht benötigt werden. \n\n"
           "Im Themenfeld ‚IT-Sicherheit‘ wurden die Antworten zwischen ‚Sehr Wenig‘ und ‚Genau richtig‘ abgegeben. "
           "Es wurden zwei der sieben Antworten für ‚Sehr Wenig‘ und vier der sieben Antworten für ‚Wenig‘ und ein "
           "der sieben Antworten für ‚Genau richtig‘ abgegeben. Das führt mich hier zu der Annahme, "
           "dass die Befragten das Angebot für nicht ausreichend halten. \n\n"
           "Im Themenfeld ‚IT-Management‘ wählten die Studenten nur die Optionen ‚Wenig‘ und ‚Genau richtig‘ aus. "
           "Dabei gab nur einer der sieben Befragten an, dass es ‚Wenig‘ Angebote gibt, während sechs der Befragten "
           "der Meinung sind, dass das Angebot ‚Genau richtig‘ sei. Draus komme ich zur Annahme, dass das Angebot im "
           "Bereich ‚IT-Management‘ für den Großteil der Studenten genau richtig ist. \n\n"
           "Im Themenfeld ‚Frontend-Entwicklung‘ gaben die Studenten Antworten in den Punkten ‚Wenig‘, "
           "‚Genau richtig‘ und ‚Viel‘ ab. Drei der Befragten waren dabei der Meinung, dass die Antwort ‚Wenig‘ am "
           "zutreffendsten ist, weitere drei der Befragten waren der Meinung, dass ‚Genau richtig‘ am besten zutrifft "
           "und ein Befragter gab an, dass die Option ‚Viel‘ ihre Meinung am besten widerspiegelt. Anhand der "
           "Ergebnisse lässt sich hier annehmen, dass eine leichte Erhöhung des Angebotes mehr Studenten "
           "zufriedenstellen würde, als es Studenten unzufrieden machen würden. \n\n"
           "Im Themenfeld ‚Backend-Entwicklung‘ gaben die Studenten Antworten in den Punkten ‚Genau richtig‘, "
           "‚Viel‘ und ‚Sehr Viel‘ ab. Im Vergleich zur ‚Frontend-Entwicklung‘ haben sich hier die Antworten um eine "
           "Kategorie gleichmäßig nach oben verschoben. Also drei antworten für ‚Genau richtig‘ und ‚Viel‘ und eine "
           "Antwort für ‚Sehr Viel‘. Demnach lässt sich annehmen, dass ‚Backend-Entwicklung‘ ein zu großes Angebot "
           "hat, welches leicht reduziert werden könnte, um mehr Platz für andere Themen zu schaffen. \n\n"
           "Dadurch dass in allen Themen die Spanne der Antworten nie größer als drei ist, ist anzunehmen, "
           "dass die generelle Tendenz von allen Studenten als gleich wahrgenommen wird und die Ergebnisse "
           "aussagekräftig sind. Im gesamten ergibt sich daher das Bild, dass die Studenten einen Mangel an Angeboten "
           "im Bereich Hardware und der IT-Sicherheit sehen, sich ein bisschen mehr Frontend-Entwicklung wünschen "
           "würden und dafür gerne weniger Backend-Entwicklung machen würden. Mit den anderen Bereichen scheinen die "
           "Studenten zufrieden zu sein."
           "\n\n"
           "### Autor: Timon Kirch\n")