# Created by Marcel Khan on 17.01.26.

"""
Auswertungen aus der Umfrage von
"Evaluation des Studiengangs Informatik (B.A.) - Studentische Perspektiven für die Reakkreditierung an der TH-Köln"
"""

TITEL = "Welche Erwartungen hattest du ins Studium und wurden diese bisher erfüllt?"

CONTENT = ("### In diesem Knoten werden die Ergebnisse der Befragung zur Frage der Erwartungen an das Studium und deren "
           "Erfüllung gesammelt. \n"
           "Insgesamt haben wir zu dieser Umfrage 7 Antworten erhalten. \n\n"
           "### Antworten: \n"
           "- Ich hatte die Erwartung zu lernen wie man Programme nach Anforderungen erstellt und dass ich weitere "
           "Programmiersprachen außerhalb von Java lernen würde. \n"
           "Das Erstellen von Programmen nach Anforderungen wurde mir gut vermittelt. Andere Programmiersprachen wurden "
           "in Fächern zwar angeboten, jedoch fehlten mir hier "
           "oftmals Einführungen in diese um mit ihnen arbeiten zu können. \n\n"
           "- Ich habe ein Praxisnahes Studium erwartet und bis auf ein paar organisatorische Punkte bin ich mit meinem "
           "Studium Sehr zufrieden! \n\n"
           "- Ja, größtenteils. Ich fand IT-Security kommt ein bisschen zu kurz. \n\n"
           "- Tieferes Verständnis der theoretischen Grundlagen sowie Erwerb praktischer Expertise – beides Erfüllt. \n\n"
           "- Ich habe mich nach der Schule gefreut, mehr über die Informatik mit gleichgesinnten zu lernen und wurde "
           "bisher nicht enttäuscht. \n\n"
           "- Keine Erwartungen, aber positiv überrascht. \n\n"
           "- diese wurden erfüllt. \n\n"
           "### Qualitative Gesamtauswertung zu der Frage: \n"
           "Die Antworten auf die Frage nach den Erwartungen an das Studium und deren Erfüllung zeichnen insgesamt ein "
           "überwiegend positives Bild des Studiengangs Informatik. Die Mehrheit der Befragten gibt an, dass ihre Erwartungen "
           "ganz oder größtenteils erfüllt wurden. Dabei lassen sich mehrere wiederkehrende Themenfelder identifizieren. \n\n"
           "Ein zentrales positives Motiv ist die Vermittlung grundlegender Kompetenzen. Mehrere Studierende heben hervor, "
           "dass sowohl das Verständnis theoretischer Grundlagen als auch die Fähigkeit zur praktischen Umsetzung "
           "erfolgreich vermittelt werden. Insbesondere das Arbeiten nach Anforderungen, also das strukturierte Entwickeln "
           "von Programmen auf Basis vorgegebener Spezifikationen, wird explizit als erfüllt beschrieben. Dies deutet "
           "darauf hin, dass zentrale Lernziele des Studiengangs aus Studierendensicht erreicht werden. \n\n"
           "Ebenfalls positiv bewertet wird die allgemeine Studienatmosphäre. Einzelne Antworten betonen das Lernen mit "
           "Gleichgesinnten sowie eine insgesamt positive Überraschung über Inhalte und Struktur des Studiums, selbst "
           "bei ursprünglich fehlenden Erwartungen. Diese Aussagen lassen auf eine hohe Grundzufriedenheit schließen, "
           "die nicht ausschließlich an konkrete Module gebunden ist, sondern auch soziale und motivationale "
           "Aspekte umfasst. \n\n"
           "Kritische Anmerkungen betreffen vor allem zwei Punkte. Zum einen wird die Einführung in zusätzliche "
           "Programmiersprachen als unzureichend beschrieben. Zwar werden verschiedene Sprachen angeboten, jedoch "
           "fehlen aus Sicht einzelner Studierender systematische Einführungen, die einen produktiven Einstieg "
           "ermöglichen würden. Zum anderen wird der Bereich IT-Security als unterrepräsentiert wahrgenommen. "
           "Diese Kritik bleibt zwar punktuell, verweist jedoch auf einen potenziellen strukturellen Schwachpunkt "
           "im Curriculum. \n\n"
           "Zusammenfassend zeigt die Umfrage eine klare Tendenz zur Zufriedenheit, ergänzt durch konkrete "
           "Verbesserungsvorschläge, die sich vor allem auf inhaltliche Schwerpunktsetzungen und didaktische Ausgestaltung "
           "beziehen. \n\n"
           "### Autor: Marcel Khan\n")