
TITEL= "Welche Inhalte hast du als veraltet,irrelevant oder schlecht vermittelt erlebt?"

CONTENT= ("In der Befragung haben viele Theoretische Informatik als veraltet/ irrelevant oder schlecht vermittelt wurde,\n"
              "was Sinn macht, wenn es bei der letzten Frage als trocken empfunden wurde beachtet. Andere Module waren Algorithmen und Programmierung 1,\n"
              " weil es viel Zeit in veraltete Werkzeuge wie C in VIM investiert wurde.\n"
              " Es wurde auch geäußert das in Einführung in Betriebs und Rechensysteme die Veranstaltung schwer zu folgen war was sich verbessern könnte.\n"
              " Einer fand das Structured Query Language (gek. SQL) das es veraltet, irrelevant oder schlecht vermittelt wurde.\n"
              " Das letzte Modul war Informatik und Gesellschaft was der Befragte fand das es thematisch wichtig ist aber\n"
              " man musste sich wirklich damit auseinandergesetzt werden zudem wurde der Fakt das es aus Pflichtvorlesungen,\n"
              " die von Gästen gehalten wurden, welche teilweise sehr anstrengend zum Zuhören waren."
              "Fazit zur ModulbewertungDie Befragungsergebnisse verdeutlichen eine signifikante Unzufriedenheit mit der Aktualität\n"
              " und der didaktischen Aufbereitung zentraler Lehrinhalte.\n"
              " Im Fokus der Kritik stehen insbesondere die Theoretische Informatik sowie SQL,\n"
              " die aufgrund veralteter Konzepte oder einer mangelhaften Vermittlung als wenig relevant für die moderne Praxis wahrgenommen werden.\n"
              " Diese Einschätzung deckt sich mit der Wahrnehmung der Algorithmen und Programmierung 1,\n"
              " bei der der hohe Zeitaufwand für technologisch überholte Werkzeuge (wie C in VIM) moniert wird.\n"
              "Zusätzlich identifiziert die Auswertung Optimierungspotenzial in der Strukturierung komplexer Module wie Einführung in Betriebs- und Rechensysteme,\n"
              " um die Verständlichkeit der Vorlesungen zu erhöhen.\n"
              " Auch das inhaltlich als wichtig anerkannte Fach Informatik und Gesellschaft leidet unter der Qualität der Durchführung;\n"
              " hier werden insbesondere die mangelnde didaktische Qualität externer Gastvorträge sowie ein zu hoher,\n"
              " unstrukturierter Arbeitsaufwand kritisiert. Insgesamt lässt sich eine klare Forderung nach moderneren Werkzeugen\n"
              " und einer ansprechenderen Wissensvermittlung ableiten.\n"
              "###Autor: Daniel Hans Gabor")