# Created by Timon Kirch on 17.01.2026

"""
Auswertungen aus der Umfrage von
"Evaluation des Studiengangs Informatik (B.A.) - Studentische Perspektiven für die Reakkreditierung an der TH-Köln"
"""

TITEL = "Auswertung - Wie würdest du die Angebote in den jeweiligen Themenbereichen anhand der Qualität bewerten??"

CONTENT = ("### Auswertung des Diagramms: Wie würdest du die Angebote in den jeweiligen Themenbereichen anhand der "
           "Qualität bewerten? \n\n"
           "In unserer Umfrage wurde den Studenten die Frage gestellt, inwieweit sie mit der Qualität der Angebote in "
           "bestimmten Themenbereichen zufrieden sind. Die Themenbereiche waren ‚Hardware‘, ‚KI‘, ‚IT-Sicherheit‘, "
           "‚IT-Management‘, ‚Frontend-Entwicklung‘ und ‚Backend-Entwicklung‘. Sie konnten die Themen als ‚Sehr "
           "Schlecht‘, ‚Schlecht‘, ‚Ok‘, ‚Gut‘ und ‚Sehr Gut‘ bewerten. \n\n"
           "Im Themenfeld ‚Hardware‘ reichen die "
           "Antworten von ‚Schlecht‘ bis ‚Gut‘, wobei ein Siebtel die Antwort ‚Gut‘ wählten und die anderen beiden "
           "Antworten von jeweils drei Siebteln gewählt wurden. Daher lässt sich annehmen, dass eine Verbesserung der "
           "Qualität nötig wäre, da nur ein kleiner Teil der Befragten tatsächlich zufrieden ist. \n\n"
           "Im Themenfeld ‚KI‘ "
           "verteilten sich die Antworten etwas breiter von ‚Schlecht‘ bis ‚Sehr gut. ‚Schlecht‘ und ‚Sehr Gut‘ gaben "
           "jeweils ein Siebtel der Befragten an. Zwei Drittel gaben an, dass die Qualität der Angebote ‚Ok‘ seien "
           "und der größte Teil mit drei Siebteln bewertete die Qualität als ‚Gut‘. Da nur ein siebtel der Stimmen "
           "unterhalb der neutralen Antwort liegen und vier Siebtel darüber, lässt das Ergebnis die Annahme zu, "
           "dass die Qualität der Angebote im Themenbereich KI keine dringende Verbesserung benötigt, jedoch noch "
           "Ausbau fähig ist. \n\n"
           "Im Themenfeld ‚IT-Sicherheit‘ wurden die Antworten zwischen ‚Schlecht‘ und ‚Gut‘ "
           "abgegeben. Es wurde eine der sieben Antworten für ‚Schlecht‘ abgeben. Die restlichen Befragten gaben zu "
           "gleichen Teilen die Antworten ‚Ok‘ und ‚Gut‘. Das führt hier zu einer ähnlichen Annahm wie zuvor. Keiner "
           "der Befragten scheint übermäßig begeistert von der Qualität zu sein, doch ist nur ein kleiner Teil "
           "tatsächlich unzufrieden. Eine dringende Verbesserung scheint auch bei der Qualität des Themenfelds "
           "IT-Sicherheit nötig zu sein. \n\n"
           "Im Themenfeld ‚IT-Management‘ liegt nur eine kleine Verteilung der Antworten "
           "vor. Alle Befragten bewerteten die Qualität von IT-Management entweder mit ‚Ok‘ oder ‚Gut‘, "
           "wobei der größere Teil mit vier Siebteln ‚Gut‘ wählte. Dies führt zu der Annahme, dass die Qualität des "
           "Themenfeldes IT-Management momentan keine Verbesserung benötigt. \n\n"
           "Im Themenfeld ‚Frontend-Entwicklung‘ "
           "gaben die Studenten Antworten in den Punkten ‚Schlecht‘, ‚Ok‘ und ‚Gut‘ ab. Einer der Befragten gab an, "
           "dass die Qualität des Angebots ‚Schlecht‘ sei. Zwei der Befragten bewerteten die Qualität als ‚Gut‘ und "
           "vier der Befragten bewerteten sie als ‚Gut‘.  Diese Antworten führen zu der Schlussfolgerung, "
           "dass eine Verbesserung empfehlenswert sei. \n\n"
           "Im Themenfeld ‚Backend-Entwicklung‘ lagen die Bewertungen nah "
           "beieinander und variierten von ‚Ok‘ bis ‚Sehr Gut‘. Jeweils zwei der Befragten bewerteten die Qualität "
           "dieses Themenbereichs als ‚Ok‘ und ‚Sehr Gut‘ und drei Befragte gaben an, dass sie ‚Gut‘ sei. \n\n"
           "Wenn es um "
           "die Qualität der Angebote geht, zeigen die Ergebnisse etwas größere Spannen der Antworten als bei der "
           "vorherigen Frage, jedoch sind ist es jeweils nur ein kleiner Teil der Stimmen, der am weitesten vom Rest "
           "ausschlägt. Dies führt zu der Annahme, dass die generelle Tendenz der Studenten als annähernd gleich "
           "wahrgenommen wird und die Ergebnisse aussagekräftig sind. IT-Management und Backend-Entwicklung scheinen "
           "die einzigen Themenfeld zu sein, die momentan keinerlei Verbesserungen der Qualität benötigen. Am "
           "dringendsten erscheint die Verbesserung der Qualität im Themenfeld Hardware und danach sollten die "
           "restlichen Themenfelder betrachtet werden, um nach möglichen Verbesserungen zu schauen. Dadurch wäre es "
           "möglich die Gewichtung von den negativen und neutralen Meinungen zu positiven zu ändern."
           "\n\n"
           "### Autor: Timon Kirch\n")